# Generated by Django 2.2 on 2019-05-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название альбома')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('image', models.URLField(default='', max_length=300, verbose_name='Ссылка на Обложку альбома')),
            ],
        ),
    ]
